name: "[CI] Pull Request"

on: pull_request

permissions:
  contents: read # the config file
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  call-lint:
    name: Call lint.yml
    uses: mateusfg7/mateusf.com/.github/workflows/lint.yml@main

  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      # follows semantic versioning. Lock to different version: v1, v1.5, v1.5.0 or use a commit hash.
      - uses: fuxingloh/multi-labeler@v2 # v2
        with:
          config-path: .github/labeler.yml # optional, default to '.github/labeler.yml'
