name: "[CI] Push Dev"

on:
  push:
    branches:
      - dev

jobs:
  call-sync-main:
    name: Call sync-main-branch.yml
    uses: mateusfg7/mfg-b/.github/workflows/sync-main-branch.yml@main
    if: startsWith(github.event.head_commit.message, "chore(release)")

  call-lint:
    name: Call lint.yml
    uses: mateusfg7/mfg-b/.github/workflows/lint.yml@main

