name: Generate Pagespeed Metrics

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
        description: Target website that will be analysed
      pwa:
        type: boolean
        default: false
        description: Enable PWA tests
  workflow_dispatch:
    inputs:
      target:
        type: string
        required: true
        description: Target website that will be analysed
      pwa:
        type: boolean
        default: false
        description: Enable PWA tests

jobs:
  generate-metrics:
    name: Generate metrics
    runs-on: ubuntu-latest
    steps:
      - name: Succinct report
        uses: lowlighter/metrics@latest
        with:
          filename: .github/assets/pagespeed-metrics.svg
          token: NOT_NEEDED
          committer_message: "docs(pagespeed-metrics): update metrics [skip ci]"
          optimize: svg, css
          experimental_features: --optimize-svg

          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: ${{ inputs.target }}
          plugin_pagespeed_pwa: ${{ inputs.pwa == true && 'yes' || 'no' }}
