name: Temp worflow to test things

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git branch --list
      - run: git checkout prod
      - run: git branch --list
