name: Temp worflow to test things

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git branch --list
      - run: git merge prod
      - run: git checkout prod
      - run: git branch --list
      - run: git log | head
      - run: git merge --squash main && git commit -m 'RELEASE KRL v2'
      - run: git log | head
      - run: git push origin prod
